name: test-unit

on:
  - push
  - pull_request

jobs:
  reflect:
    runs-on: ubuntu-latest
    steps:
      - name: current ref
        run: echo ${{ github.ref }}
      - name: HEAD ref
        run: echo ${{ github.head_ref }}
      - name: python version
        run: python --version
      - name: pip version
        run: pip --version

  collect-code:
    runs-on: ubuntu-latest
    steps:
      - name: gather code
        uses: actions/checkout@v2
        with:
          path: ./terraform-compose
      - name: artifact code
        uses: actions/upload-artifact@v3
        with:
          name: terraform-compose
          path: ./terraform-compose

  run-tests:
    runs-on: ubuntu-latest
    needs:
      - collect-code
    steps:
      - name: download terraform-compose
        uses: actions/download-artifact@v3
        with:
          name: terraform-compose
          path: terraform-compose
      - name: install depends
        run: pip install $(cat ./terraform-compose/requirements.*)
      - name: run tests
        env:
          PYTHON_PATH: ./terraform-compose
        run: python -m pytest -vv --cov
